version: '3.8'

services:
    redis:
        container_name: redis
        image: redis/redis-stack
        ports:
            - "16379:6379"
        volumes:
            - ./data:/data

    app:
        container_name: app
        build:
            context: .
            dockerfile: DockerfileLocal
        env_file:
            - .env
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app/app
        depends_on:
            - redis
    # test:
    #     build:
    #         context: .
    #         dockerfile: DockerfileLocal
    #     volumes:
    #         - ./tests:/tests
    #     depends_on:
    #         - redis
    #     entrypoint: [ "pytest" ]
